### REST client routes for the contacts API

@baseUrl = http://localhost:3001

### Home page
GET http://localhost:3001
Accept: text/html

### Get all contacts
GET http://localhost:3001/
Accept: application/json

### Get one contact by id
GET http://localhost:3001/6a0dfe505b413bcf50ba2e3f
Accept: application/json

### Create a new contact
POST http://localhost:3001/courses/ HTTP/1.1
Content-Type: application/json

 {
    "firstName": "Nathan",
    "lastName": "Barker",
    "email": "barkern@byui.edu",
    "department": "Computer Science & Engineering",
    "officeLocation": "STC 312"
  }

### Update a contact by id
PUT http://localhost:3001/courses/6a0c20bb9d57c87818cf1337 HTTP/1.1
Content-Type: application/json

 {
    "courseTitle": "Advanced Backend Development",
    "courseId": "CSE 341",
    "instructor": "Brother Nathan",
    "classMax": 55,
    "currentEnrollment": 48,
    "startDate": "2026-04-20",
    "endDate": "2026-07-24"
  }

### Delete a contact by id
DELETE http://localhost:3001/6a135784aacd9532d547b394oiut

### Render HTML contacts list
GET http://localhost:3001/
Accept: text/html
